version: '3'
services:
  ### Database
  db:
    image: mongo
    volumes:
      - ./volumes/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: login
      MONGO_INITDB_ROOT_PASSWORD: password
  ### Database viewer
  db-viewer:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: login
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #Server
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    links:
      - db
    environment:
      PORT: 8000
      APP_VARIANT: INTERNAL
      PRESHARED_GATEWAY_KEY: GATEWAY_PRESHARED
      MONGO_URL: 'mongodb://login:password@db:27017'
